<?php

	/*DEFINED*/

	$exclude = array( 'id', 'created', 'nama_penghasilan_tambahan', 'id', 'id_data_lembaga' );
	function alias( $text ) {
		$data = array(
			'rt' => "RT",
			'rw' => 'RW',
			'rt_perusahaan' => 'RT',
			'rw_perusahaan' => 'RW',
			'kelurahan_perusahaan' => 'Kelurahan',
			'kecamatan_perusahaan' => 'Kecamatan',
			'kota_perusahaan' => 'Kota',
			'kodepos_perusahaan' => 'Kodepos',
			'provinsi_perusahaan' => 'Propinsi',
			'tlp_perusahaan' => 'Telepon',
			'fax_perusahaan' => 'Faximile',
			'website_perusahaan' => 'Website',
			'email_perusahaan' => 'Email',
			'rt_saat_ini' => 'RT',
			'rw_saat_ini' => 'RW',
			'kelurahan_saat_ini' => 'Kelurahan',
			'kecamatan_saat_ini' => 'Kecamatan',
			'kota_saat_ini' => 'Kota',
			'kodepos_saat_ini' => 'Kodepos',
			'propinsi_saat_ini' => 'Propinsi',
			'no_npwp' => 'No NPWP',
			'no_ktp' => 'No KTP',
			'wni' => 'WNI',
			'wna' => 'WNA',
			'laki-laki' => 'Laki - Laki',
			'atm' => 'ATM',
			'kos' => 'Kost',
			'perorangan' => 'Perorangan',
			'lembaga' => 'Lembaga',
		);
		if ( ! empty( $data[$text] ) ) {
			return $data[$text];
		} else {
			return $text;
		}
	}

	$pribadi['Data Pribadi']['nama_sesuai_identitas'] = 'nama_sesuai_identitas';
	$pribadi['Data Pribadi']['nama_tanpa_gelar'] = 'nama_tanpa_gelar';
	$pribadi['Data Pribadi']['gelar_sebelum_nama'] = 'gelar_sebelum_nama';
	$pribadi['Data Pribadi']['gelar_setelah_nama'] = 'gelar_setelah_nama';
	$pribadi['Data Pribadi']['nama_alias'] = 'nama_alias';
	$pribadi['Data Pribadi']['nama_wali'] = 'nama_wali';
	$pribadi['Data Pribadi']['alamat'] = 'alamat';
	$pribadi['Data Pribadi']['alamat_sub']['rt'] = 'rt';
	$pribadi['Data Pribadi']['alamat_sub']['rw'] = 'rw';
	$pribadi['Data Pribadi']['alamat_sub']['kelurahan'] = 'kelurahan';
	$pribadi['Data Pribadi']['alamat_sub']['kecamatan'] = 'kecamatan';
	$pribadi['Data Pribadi']['alamat_sub']['kota'] = 'kota';
	$pribadi['Data Pribadi']['alamat_sub']['propinsi'] = 'propinsi';
	$pribadi['Data Pribadi']['alamat_sub']['kode_pos'] = 'kode_pos';
	$pribadi['Data Pribadi']['status_alamat'] = 'status_alamat';
	$pribadi['Data Pribadi']['alamat_saat_ini'] = 'alamat_saat_ini';
	$pribadi['Data Pribadi']['alamat_saat_ini_sub']['rt_saat_ini'] = 'rt_saat_ini';
	$pribadi['Data Pribadi']['alamat_saat_ini_sub']['rw_saat_ini'] = 'rw_saat_ini';
	$pribadi['Data Pribadi']['alamat_saat_ini_sub']['kelurahan_saat_ini'] = 'kelurahan_saat_ini';
	$pribadi['Data Pribadi']['alamat_saat_ini_sub']['kecamatan_saat_ini'] = 'kecamatan_saat_ini';
	$pribadi['Data Pribadi']['alamat_saat_ini_sub']['kota_saat_ini'] = 'kota_saat_ini';
	$pribadi['Data Pribadi']['alamat_saat_ini_sub']['propinsi_saat_ini'] = 'propinsi_saat_ini';
	$pribadi['Data Pribadi']['alamat_saat_ini_sub']['kodepos_saat_ini'] = 'kodepos_saat_ini';
	$pribadi['Data Pribadi']['status_alamat_saat_ini'] = 'status_alamat_saat_ini';
	$pribadi['Data Pribadi']['tahun_lama_tinggal'] = 'tahun_lama_tinggal';
	$pribadi['Data Pribadi']['bulan_lama_tinggal'] = 'bulan_lama_tinggal';
	$pribadi['Data Pribadi']['no_tlp_1'] = 'no_tlp_1';
	$pribadi['Data Pribadi']['no_tlp_2'] = 'no_tlp_2';
	$pribadi['Data Pribadi']['ponsel'] = 'ponsel';
	$pribadi['Data Pribadi']['email'] = 'email';
	$pribadi['Data Pribadi']['tempat_lahir'] = 'tempat_lahir';
	$pribadi['Data Pribadi']['tgl_lahir'] = 'tgl_lahir';
	$pribadi['Data Pribadi']['warganegara'] = 'warganegara';
	$pribadi['Data Pribadi']['negara_asal'] = 'negara_asal';
	$pribadi['Data Pribadi']['jenis_kelamin'] = 'jenis_kelamin';
	$pribadi['Data Pribadi']['status_penduduk'] = 'status_penduduk';
	$pribadi['Data Pribadi']['id_pengenal'] = 'id_pengenal';
	$pribadi['Data Pribadi']['no_pengenal'] = 'no_pengenal';
	$pribadi['Data Pribadi']['diterbitkan_pengenal'] = 'diterbitkan_pengenal';
	$pribadi['Data Pribadi']['masa_berlaku_pengenal'] = 'masa_berlaku_pengenal';
	$pribadi['Data Pribadi']['id_pengenal_tambahan'] = 'id_pengenal_tambahan';
	$pribadi['Data Pribadi']['no_pengenal_tambahan'] = 'no_pengenal_tambahan';
	$pribadi['Data Pribadi']['diterbitkan_pengenal_tambahan'] = 'diterbitkan_pengenal_tambahan';
	$pribadi['Data Pribadi']['agama'] = 'agama';
	$pribadi['Data Pribadi']['status_kawin'] = 'status_kawin';
	$pribadi['Data Pribadi']['jumlah_anak'] = 'jumlah_anak';
	$pribadi['Data Pribadi']['jumlah_tanggungan'] = 'jumlah_tanggungan';
	$pribadi['Data Pribadi']['pendidikan'] = 'pendidikan';
	$pribadi['Data Pribadi']['nama_gadis_ibu_kandung'] = 'nama_gadis_ibu_kandung';
	$pribadi['Data Pribadi']['nama_lengkap_relasi'] = 'nama_lengkap_relasi';
	$pribadi['Data Pribadi']['alamat_relasi'] = 'alamat_relasi';
	$pribadi['Data Pribadi']['no_tlp_relasi'] = 'no_tlp_relasi';
	$pribadi['Data Pribadi']['hubungan_nasabah'] = 'hubungan_nasabah';
	$pribadi['Data Pekerjaan']['bidang_usaha'] = 'bidang_usaha';
	$pribadi['Data Pekerjaan']['jenis_pekerjaan'] = 'jenis_pekerjaan';
	$pribadi['Data Pekerjaan']['jabatan'] = 'jabatan';
	$pribadi['Data Pekerjaan']['nama_perusahaan'] = 'nama_perusahaan';
	$pribadi['Data Pekerjaan']['alamat_perusahaan'] = 'alamat_perusahaan';
	$pribadi['Data Pekerjaan']['alamat_perusahaan_sub']['rt_perusahaan'] = 'rt_perusahaan';
	$pribadi['Data Pekerjaan']['alamat_perusahaan_sub']['rw_perusahaan'] = 'rw_perusahaan';
	$pribadi['Data Pekerjaan']['alamat_perusahaan_sub']['kelurahan_perusahaan'] = 'kelurahan_perusahaan';
	$pribadi['Data Pekerjaan']['alamat_perusahaan_sub']['kecamatan_perusahaan'] = 'kecamatan_perusahaan';
	$pribadi['Data Pekerjaan']['alamat_perusahaan_sub']['kota_perusahaan'] = 'kota_perusahaan';
	$pribadi['Data Pekerjaan']['alamat_perusahaan_sub']['kodepos_perusahaan'] = 'kodepos_perusahaan';
	$pribadi['Data Pekerjaan']['alamat_perusahaan_sub']['provinsi_perusahaan'] = 'provinsi_perusahaan';
	$pribadi['Data Pekerjaan']['tlp_perusahaan'] = 'tlp_perusahaan';
	$pribadi['Data Pekerjaan']['fax_perusahaan'] = 'fax_perusahaan';
	$pribadi['Data Pekerjaan']['email_perusahaan'] = 'email_perusahaan';
	$pribadi['Data Pekerjaan']['website_perusahaan'] = 'website_perusahaan';
	$pribadi['Data Penghasilan Kotor Perbulan']['penghasilan_pemohon'] = 'penghasilan_pemohon';
	$pribadi['Data Penghasilan Kotor Perbulan']['penghasilan_tambahan'] = 'penghasilan_tambahan';
	$pribadi['Data Penghasilan Kotor Perbulan']['nama_penghasilan_tambahan'] = 'nama_penghasilan_tambahan';
	// $pribadi['Identitas Tambahan']['photo']='photo';
	// $pribadi['Identitas Tambahan']['tanda_tangan']='tanda_tangan';
		
	$buka_rekening['Khusus Pembukaan Rekening Haji Nawaitu']['menghendaki_jasa_tabungan'] = 'menghendaki_jasa_tabungan';
	$buka_rekening['Khusus Pembukaan Rekening Haji Nawaitu']['tahun_berangkat'] = 'tahun_berangkat';
	$buka_rekening['Khusus Pembukaan Rekening Haji Nawaitu']['wilayah_berangkat'] = 'wilayah_berangkat';
	$buka_rekening['Khusus Penggantian Kartu BTN']['alasan_penggantian_kartu'] = 'alasan_penggantian_kartu';
	$buka_rekening['Data Nasabah']['no_cif'] = 'no_cif';
	$buka_rekening['Data Nasabah']['nama_lengkap'] = 'nama_lengkap';
	$buka_rekening['Data Nasabah']['no_rekening'] = 'no_rekening';
	$buka_rekening['Data Nasabah']['sumber_dana'] = 'sumber_dana';
	$buka_rekening['Data Nasabah']['sumber_dana_tambahan'] = 'sumber_dana_tambahan';
	$buka_rekening['Data Nasabah']['jenis_setoran'] = 'jenis_setoran';
	$buka_rekening['Data Nasabah']['tujuan_buka_rekening'] = 'tujuan_buka_rekening';
	$buka_rekening['Data Nasabah']['alasan_buka_rekening'] = 'alasan_buka_rekening';
	$buka_rekening['Fitur/Fasilitas Yang Di inginkan']['fitur'] = 'fitur';
	$buka_rekening['Fitur/Fasilitas Yang Di inginkan']['nama_pada_kartu'] = 'nama_pada_kartu';
	$buka_rekening['Khusus Deposito']['jumlah_nominal'] = 'jumlah_nominal';
	$buka_rekening['Khusus Deposito']['terbilang'] = 'terbilang';
	$buka_rekening['Khusus Deposito']['mata_uang'] = 'mata_uang';
	$buka_rekening['Khusus Deposito']['jangka_waktu'] = 'jangka_waktu';
	$buka_rekening['Khusus Deposito']['suku_bunga'] = 'suku_bunga';
	$buka_rekening['Khusus Deposito']['perpanjangan'] = 'perpanjangan';
	$buka_rekening['Khusus Deposito']['cara_pembayaran_bunga'] = 'cara_pembayaran_bunga';
	$buka_rekening['Khusus Deposito']['pemindahbukuan'] = 'pemindahbukuan';
	$buka_rekening['Khusus Deposito']['pemindahbukuan_subs']['pemindahbukuan_ke_rek'] = 'pemindahbukuan_ke_rek';

	$buka_atm['kota'] = 'kota';
	$buka_atm['cabang'] = 'cabang';
	$buka_atm['tanggal'] = 'tanggal';
	$buka_atm['nama_lengkap'] = 'nama_lengkap';
	$buka_atm['tempat_lahir'] = 'tempat_lahir';
	$buka_atm['tanggal_lahir'] = 'tanggal_lahir';
	$buka_atm['nama_gadis_ibu_kandung'] = 'nama_gadis_ibu_kandung';
	$buka_atm['alamat_lengkap'] = 'alamat_lengkap';
	$buka_atm['no_tlp_rumah'] = 'no_tlp_rumah';
	$buka_atm['no_tlp_kantor'] = 'no_tlp_kantor';
	$buka_atm['no_hp'] = 'no_hp';
	$buka_atm['no_kartu_btn'] = 'no_kartu_btn';
	$buka_atm['no_cif'] = 'no_cif';
	$buka_atm['Kartu BTN']['kartu_btn'] = 'kartu_btn';
	$buka_atm['Kartu BTN']['kartu_baru'] = 'kartu_baru';
	$buka_atm['Kartu BTN']['nama_pada_kartu'] = 'nama_pada_kartu';
	$buka_atm['Kartu BTN']['penggantian_kartu'] = 'penggantian_kartu';
	$buka_atm['Kartu BTN']['alasan_penggantian_kartu'] = 'alasan_penggantian_kartu';
	$buka_atm['Kartu BTN']['jenis_kartu'] = 'jenis_kartu';
	$buka_atm['Kartu BTN']['status_kartu_instan'] = 'status_kartu_instan';
	$buka_atm['Kartu BTN']['update_data'] = 'update_data';
	$buka_atm['SMS Banking']['sms_banking'] = 'sms_banking';
	$buka_atm['SMS Banking']['daftar_rek_tujuan_transfer'] = 'daftar_rek_tujuan_transfer';
	$buka_atm['SMS Banking']['daftar_rek_pembayaran'] = 'daftar_rek_pembayaran';
	$buka_atm['SMS Banking']['sms_alert'] = 'sms_alert';
	$buka_atm['SMS Banking']['pendebetan_lebih_dari'] = 'pendebetan_lebih_dari';
	$buka_atm['SMS Banking']['pengkreditan_lebih_dari'] = 'pengkreditan_lebih_dari';
	$buka_atm['SMS Banking']['saldo_kurang_dari'] = 'saldo_kurang_dari';
	$buka_atm['SMS Banking']['no_rek_pendebitan'] = 'no_rek_pendebitan';
	$buka_atm['SMS Banking']['no_rek_pengkreditan'] = 'no_rek_pengkreditan';
	$buka_atm['SMS Banking']['no_rek_saldo'] = 'no_rek_saldo';

	$lembaga['Data Lembaga']['nama_lembaga'] = 'nama_lembaga';
	$lembaga['Data Lembaga']['bidang_usaha'] = 'bidang_usaha';
	$lembaga['Data Lembaga']['alamat'] = 'alamat';
	$lembaga['Data Lembaga']['alamat_sub']['rt'] = 'rt';
	$lembaga['Data Lembaga']['alamat_sub']['rw'] = 'rw';
	$lembaga['Data Lembaga']['alamat_sub']['kelurahan'] = 'kelurahan';
	$lembaga['Data Lembaga']['alamat_sub']['kecamatan'] = 'kecamatan';
	$lembaga['Data Lembaga']['alamat_sub']['kota'] = 'kota';
	$lembaga['Data Lembaga']['alamat_sub']['provinsi'] = 'provinsi';
	$lembaga['Data Lembaga']['alamat_sub']['kode_pos'] = 'kode_pos';
	$lembaga['Data Lembaga']['no_tlp'] = 'no_tlp';
	$lembaga['Data Lembaga']['no_fax'] = 'no_fax';
	$lembaga['Data Lembaga']['email'] = 'email';
	$lembaga['Data Lembaga']['website'] = 'website';
	$lembaga['Legalitas Lembaga']['no_npwp'] = 'no_npwp';
	$lembaga['Legalitas Lembaga']['no_anggaran_dasar'] = 'no_anggaran_dasar';
	$lembaga['Legalitas Lembaga']['no_akta_pendirian'] = 'no_akta_pendirian';
	$lembaga['Legalitas Lembaga']['tanggal_akta_pendirian'] = 'tanggal_akta_pendirian';
	$lembaga['Legalitas Lembaga']['diterbitkan_akta_pendirian'] = 'diterbitkan_akta_pendirian';
	$lembaga['Legalitas Lembaga']['notaris_akta_pendirian'] = 'notaris_akta_pendirian';
	$lembaga['Legalitas Lembaga']['no_akta_perubahan'] = 'no_akta_perubahan';
	$lembaga['Legalitas Lembaga']['tanggal_akta_perubahan'] = 'tanggal_akta_perubahan';
	$lembaga['Legalitas Lembaga']['diterbitkan_akta_perubahan'] = 'diterbitkan_akta_perubahan';
	$lembaga['Legalitas Lembaga']['notaris_akta_perubahan'] = 'notaris_akta_perubahan';
	$lembaga['Legalitas Lembaga']['no_siup'] = 'no_siup';
	$lembaga['Legalitas Lembaga']['tanggal_siup'] = 'tanggal_siup';
	$lembaga['Legalitas Lembaga']['diterbitkan_siup'] = 'diterbitkan_siup';
	$lembaga['Legalitas Lembaga']['siup_masa_berlaku'] = 'siup_masa_berlaku';
	$lembaga['Legalitas Lembaga']['no_tdp'] = 'no_tdp';
	$lembaga['Legalitas Lembaga']['tanggal_tdp'] = 'tanggal_tdp';
	$lembaga['Legalitas Lembaga']['diterbitkan_tdp'] = 'diterbitkan_tdp';
	$lembaga['Legalitas Lembaga']['tdp_masa_berlaku'] = 'tdp_masa_berlaku';
	$lembaga['Legalitas Lembaga']['no_situ'] = 'no_situ';
	$lembaga['Legalitas Lembaga']['tanggal_situ'] = 'tanggal_situ';
	$lembaga['Legalitas Lembaga']['diterbitkan_situ'] = 'diterbitkan_situ';
	$lembaga['Legalitas Lembaga']['situ_masa_berlaku'] = 'situ_masa_berlaku';
	$lembaga['Data Pengurus Lembaga'] = array('relation' => 'btn_data_pengurus_lembaga');
	$lembaga['Group Usaha'] = array('relation' => 'btn_group_usaha_lembaga'); 

	$cif['Head']['reg_id'] = 'Reg ID';
	$cif['Head']['jenis_cif'] = 'Jenis CIF';
	$cif['Head']['nama'] = 'Nama';
?>